<!DOCTYPE html>
<html>
    </body>
        <p align=justify>
            Hello, TapTap is here to alert <b>{RECEIVER_EMAIL} ({USER}) from {SCHOOL_NAME} of possible breach alert.</b><br><br>
            Your device has been receiving various passphrase mismatch. Due to the setup of device, it is shutting down as you receive this email. You can access it later on.
        </p>

        <p align=justify>
            If you are not trying to access, ignore this email. The details of the computer are:<br><br>User: <i>{USER}</i><br>HOSTNAME: <i>{HOSTNAME}</i><br>IP address: <i>{IP_ADDR}</i><br>Tracked from:<i> {LOC}) at {DATETIME}</i>.
        </p>

        <p align=justify>
            This was done as security measure, the email in situation that met the criterion is inevitable.<br><blockquote>Cheers,<br>TapTap team</blockquote>
        </p>
    </body>
</html>
