<!DOCTYPE html>
<html>
    </body>
        <p align=justify>
            Hello, TapTap is here to deliver the secure passphrase requested by: <b>{RECEIVER_EMAIL} ({USER}) from {SCHOOL_NAME}.</b>,<br><br>
            <em>DO NOT SHARE THIS CODE FOR USE IN SETUP/GIT PULL OF THE DATABASE</em>. This is the secure phrase for your access of the student and teacher data in repository setup: <br><br><center><b><code>{phrase}</code></b></center>
        </p>

        <p align=justify>
            If you are not trying to access, ignore this email. The details of the computer are:<br><br>User: <i>{USERNAME}</i><br>HOSTNAME: <i>{HOSTNAME}</i><br>IP address: <i>{IP_ADDR}</i><br>Tracked from: <i>{LOC}) at {DATETIME}</i>.<blockquote>Cheers,<br>TapTap team</blockquote>
        </p>
    </body>
</html>
