<!DOCTYPE html>
<html>
    </body>
        <p align=justify>
            Hello, TapTap is here to alert <b>{RECEIVER_EMAIL} ({USER}) from {SCHOOL_NAME} of possible intruder at {DATETIME}.</b><br><br>
        </p>

        <p align=justify>
            This was done as security measure, the email in situation that met the criterion is inevitable.<br><blockquote>Cheers,<br>TapTap team</blockquote>
        </p>
    </body>
</html>
